# Generated by Django 5.0.9 on 2024-11-29 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalseccioncliente',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informacioncliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacion', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='seccioncliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='tablacliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablas', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='tablacliente',
            name='seccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tablas', to='clientes.seccioncliente'),
        ),
        migrations.AddField(
            model_name='filatabla',
            name='tabla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='clientes.tablacliente'),
        ),
    ]
