# Generated by Django 5.0.9 on 2024-11-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='logo',
            field=models.ImageField(blank=True, default='logos/default_logo.jpg', upload_to='logos/'),
        ),
    ]
